name: Manual Testing
on:
  workflow_dispatch:
    inputs:
      networkNodeTag:
        description: 'Specify desired Network Node image tag'
        required: true
        default: ''
      mirrorNodeTag:
        description: 'Specify desired Mirror-Node image tag'
        required: true
        default: ''
      relayTag:
        description: 'Specify desired Hedera JSON-RPC Relay tag'
        required: true
        default: ''
run-name: Manual Test with N:${{ inputs.networkNodeTag }}, M:${{ inputs.mirrorNodeTag }} and R:${{ inputs.relayTag }}

permissions:
  contents: read
  checks: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  ERC20Contract:
    name: ERC20 Contract Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: ERC20
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  ERC721Contract:
    name: ERC721 Contract Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: ERC721
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  ERC1155Contract:
    name: ERC1155 Contract Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: ERC1155
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  TokenCreateContract:
    name: Token Create Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: TokenCreateContract
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  TokenQueryContract:
    name: Token Query Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: TokenQueryContract
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  TokenManagmentContract:
    name: Token Managment Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: TokenManagmentContract
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  TokenTransferContract:
    name: Token Transfer Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: TokenTransferContract
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  Proxy:
    name: Proxy Upgrade Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: Proxy
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  SafeHTS:
    name: SafeHTS Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: SafeHTS
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  HIP583:
    name: HIP583 Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: HIP583
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  Multicall:
    name: Multicall Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: Multicall
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  HRC:
    name: HRC Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: HRC
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  ShanghaiOpcodes:
    name: ShanghaiOpcodes Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: ShanghaiOpcodes
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  PrngSystemContract:
    name: PrngSystemContract Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: PrngSystemContract
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  SolidityEquivalence1:
    name: Solidity Equivalence Suite 1
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: 'solidityequiv1'
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  SolidityEquivalence2:
    name: Solidity Equivalence Suite 2
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: 'solidityequiv2'
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  SolidityEquivalence3:
    name: Solidity Equivalence Suite 3
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: 'solidityequiv3'
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  YulEquiv:
    name: Yul Equivalence
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: 'yulequiv'
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}

  OpenZeppelinEquiv:
    name: OpenZeppelin Equivalence
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: 'OZ'
      networkTag: ${{inputs.networkNodeTag}}
      mirrorTag: ${{inputs.mirrorNodeTag}}
      relayTag: ${{inputs.relayTag}}
